Neos:
  Ldap:
    roles:
      # default roles to give each user
      default: []
#        - 'Neos.Neos:RestrictedEditor'
      # map group memberships to roles
      groupMapping: []
#        'Neos.Neos:Administrator':
#          - 'CN=Administrators,OU=Groups,DC=domain,DC=tld'
#        'Neos.Neos:Editor':
#          - 'CN=Editors,OU=Groups,DC=domain,DC=tld'
      # map certain users to roles
      userMapping: []
#        'Neos.Neos:Administrator':
#          - 'CN=Admin,OU=Users,DC=domain,DC=tld'
#        'Neos.Neos:Editor':
#          - 'CN=Mustermann,OU=Users,DC=domain,DC=tld'
